#- name: Demo my first playbook, Play1
#  hosts: all
#  tasks:
#    - name: Print Hello
#      ansible.builtin.debug:
#        msg: Hello How are you
#
#- name: Demo my first playbook, Play2
#  hosts: all
#  tasks:
#    - name: Print Hello
#      ansible.builtin.debug:
#        msg: Hello How are you
#
#- name: demo app3
#  hosts: all
#  tasks:
#    - name : print rahul
#      ansible.builtin.debug:
#        msg: hello_rahul?
#
#- name:  demp app4
#  hosts: all
#  roles:
#    - sample


- name: sample condition
  hosts: all
  tasks:
    - name:  checking condition
      ansible.builtin.debug:
        msg: "{{item}}"
      loop:
        - orange
        - grape

- name: when condition
  hosts: all
  tasks:
    - name:  Redhat
      ansible.builtin.debug:
        msg: This is RedHat family
      when: ansible_os_family == "RedHat"
    - name: Debain
      ansible.builtin.debug:
        msg: this is debain
      when: ansible_os_family == "Debain"


- name: logical
  hosts: all
  tasks:
    - name:  Redhat
      ansible.builtin.debug:
        msg: "{{ansible_distribution,ansible_distribution_major_version}}"
      when: ansible_os_family == "RedHat" or ansible_distribution_major_version == "2"
    - name: Debain
      ansible.builtin.debug:
        msg: this is debain
      when: ansible_os_family == "Debain"

- name: checking uptime
  hosts: all
  tasks:
    - name: register
      ansible.builtin.shell:
        uptime
      register: uptime_output
    - name: set_fact
      ansible.builtin.set_fact:
        onefact == uptime_output