- name: Demo my first playbook, Play1

  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello How are you

- name: Demo my first playbook, Play2

  tasks:
    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello How are you

- name : demo app3
  
  tasks:
    - name : print rahul
      ansible.builtin.debug:
        msg: hello_rahul?