- name: Demo variable 1
  hosts: all
  vars:
    URL: here.ex.com
  tasks:
    - name: inside variable
      ansible.builtin.debug:
        msg: url == {{ URL }}


- name: Demo variable 2
  hosts: all

  tasks:
    - name: inside tasks
      vars:
        URL: inside.task.com
      ansible.builtin.debug:
        msg: url == {{ URL }}

- name: Demo variable 3
  hosts: all
  vars_files: d-vars.yml
  tasks:
    - name: inside file
      ansible.builtin.debug:
        msg: url == {{ URL }}