- name: Demo variable 1
  hosts: all
  vars:
    URL: here.ex.com
  tasks:
    - name: inside variable
      ansible.builtin.debug:
        msg: url == {{ URL }}


#- name: Demo on Play vars
#  hosts: all
#  vars:
#    URL: play.example.com
#  tasks:
#    - name: Print URL
#      ansible.builtin.debug:
#        msg: URL == {{ URL }}